apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aks-openapi-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aks-openapi-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aks-openapi-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default "default" }}
    namespace: {{ .Release.Namespace }}
