apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aks-openapi-operator-pod-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "serviceaccounts"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-openapi-operator-pod-reader-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aks-openapi-operator-pod-reader
subjects:
- kind: ServiceAccount
  name: {{ include "aks-openapi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
