{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aks-openapi-operator.serviceAccountName" . }}
  labels:
    {{- include "aks-openapi-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.serviceAccount.workloadIdentity.enabled .Values.serviceAccount.workloadIdentity.clientID }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.serviceAccount.workloadIdentity.clientID }}"
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
