# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{ .Values.serviceAccount.name }}
#   namespace: {{ .Release.Namespace }}
#   labels:
#     app.kubernetes.io/name: {{ include "aks-openapi-operator.name" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
