apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azure-apim-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure-apim-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apim.hedinit.io"]
    resources: ["apimapis"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apim.hedinit.io"]
    resources: ["apimapis/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apim.hedinit.io"]
    resources: ["apimapideployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]   
  - apiGroups: ["apim.hedinit.io"]
    resources: ["apimapideployments/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apim.hedinit.io"]
    resources: ["apimservices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]   
  - apiGroups: ["apim.hedinit.io"]
    resources: ["apimservices/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apim.hedinit.io"]
    resources: ["apimapipatches"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]   
  - apiGroups: ["apim.hedinit.io"]
    resources: ["apimapipatches/status"]
    verbs: ["get", "update", "patch"] 

