{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-apim-operator.serviceAccountName" . }}
  labels:
    {{- include "azure-apim-operator.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.serviceAccount.workloadIdentity.enabled .Values.serviceAccount.workloadIdentity.clientID }}
    azure.workload.identity/client-id: "{{ .Values.serviceAccount.workloadIdentity.clientID }}"
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
