---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apim.hedinit.io
  resources:
  - apimapideployments
  - apimapipatches
  - apimapis
  - apimproducts
  - apimservices
  - apimtags
  - deployapis
  - importapis
  - ingresswatchers
  - patchapis
  - replicasetwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.hedinit.io
  resources:
  - apimapideployments/finalizers
  - apimapipatches/finalizers
  - apimapis/finalizers
  - apimproducts/finalizers
  - apimservices/finalizers
  - apimtags/finalizers
  - deployapis/finalizers
  - importapis/finalizers
  - ingresswatchers/finalizers
  - patchapis/finalizers
  - replicasetwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - apim.hedinit.io
  resources:
  - apimapideployments/status
  - apimapipatches/status
  - apimapis/status
  - apimproducts/status
  - apimservices/status
  - apimtags/status
  - deployapis/status
  - importapis/status
  - ingresswatchers/status
  - patchapis/status
  - replicasetwatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
