---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apim.operator.io
  resources:
  - apimapideployments
  - apimapis
  - apiminboundpolicies
  - apimproducts
  - apimservices
  - apimtags
  - replicasetwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.operator.io
  resources:
  - apimapideployments/finalizers
  - apimapis/finalizers
  - apiminboundpolicies/finalizers
  - apimproducts/finalizers
  - apimservices/finalizers
  - apimtags/finalizers
  - replicasetwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - apim.operator.io
  resources:
  - apimapideployments/status
  - apimapis/status
  - apiminboundpolicies/status
  - apimproducts/status
  - apimservices/status
  - apimtags/status
  - replicasetwatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
