---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: apiminboundpolicies.apim.hedinit.io
spec:
  group: apim.hedinit.io
  names:
    kind: APIMInboundPolicy
    listKind: APIMInboundPolicyList
    plural: apiminboundpolicies
    singular: apiminboundpolicy
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: APIMInboundPolicy is the Schema for the apiminboundpolicies API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: APIMInboundPolicySpec defines the desired state of APIMInboundPolicy.
            properties:
              PolicyId:
                description: PolicyId is the unique identifier for the policy in APIM
                type: string
              apimService:
                description: APIMService is the name of the APIMService custom resource
                type: string
            required:
            - PolicyId
            - apimService
            type: object
          status:
            description: APIMInboundPolicyStatus defines the observed state of APIMInboundPolicy.
            properties:
              message:
                description: Message contains error details or status context
                type: string
              phase:
                description: Phase indicates lifecycle state like "Created" or "Error"
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
