---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: apimtags.apim.hedinit.io
spec:
  group: apim.hedinit.io
  names:
    kind: APIMTag
    listKind: APIMTagList
    plural: apimtags
    singular: apimtag
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: APIMTag is the Schema for the apimtags API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: APIMTagSpec defines the desired state of APIMTag.
            properties:
              apimService:
                description: APIMService is the name of the APIMService custom resource
                type: string
              displayName:
                description: DisplayName is the name shown in the APIM UI
                type: string
              tagId:
                description: TagID is the unique identifier for the tag in APIM
                type: string
            required:
            - apimService
            - displayName
            - tagId
            type: object
          status:
            description: APIMTagStatus defines the observed state of APIMTag.
            properties:
              message:
                description: Message contains error details or status context
                type: string
              phase:
                description: Phase indicates lifecycle state like "Created" or "Error"
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
