apiVersion: apim.operator.io/v1
kind: APIMProduct
metadata:
  labels:
    app.kubernetes.io/name: azure-apim-operator
    app.kubernetes.io/managed-by: kustomize
  name: apimproduct-sample
spec:
  # TODO(user): Add fields here
