apiVersion: apim.hedinit.io/v1
kind: APIMAPIRevision
metadata:
  labels:
    app.kubernetes.io/name: aks-apim-operator
    app.kubernetes.io/managed-by: kustomize
  name: APIMAPIRevision-sample
spec:
  # TODO(user): Add fields here
