apiVersion: apim.hedinit.io/v1
kind: APIMAPIDeployment
metadata:
  labels:
    app.kubernetes.io/name: azure-apim-operator
    app.kubernetes.io/managed-by: kustomize
  name: apimapideployment-sample
spec:
  # TODO(user): Add fields here
