## Append samples of your project ##
resources:
- apim_v1_apimapi.yaml
- apim_v1_apimapideployment.yaml
- apim_v1_apimservice.yaml
- apim_v1_apimproduct.yaml
- apim_v1_apimtag.yaml
- apim_v1_apiminboundpolicy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
