## Append samples of your project ##
resources:
- net_v1_ingresswatcher.yaml
- apim_v1_apimapi.yaml
- apim_v1_apimapideployment.yaml
- apim_v1_apimservice.yaml
- apim_v1_apimapipatch.yaml
- apim_v1_import.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
